services:
  nginx:
    image: nginx:alpine
    container_name: lab5_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
      - redis
      - elasticsearch
      - clickhouse
    networks:
      - lab_network

  php:
    build: .
    container_name: lab5_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db
      - redis
      - elasticsearch
      - clickhouse
    networks:
      - lab_network

  db:
    image: mysql:8.0
    container_name: lab5_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: student_db
      MYSQL_USER: student_user
      MYSQL_PASSWORD: student_pass
    ports:
      - "3307:3306"
    volumes:
      - db_/var/lib/mysql
    networks:
      - lab_network

  adminer:
    image: adminer
    container_name: lab5_adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - lab_network

  redis:
    image: redis:7-alpine
    container_name: lab6_redis
    ports:
      - "6379:6379"
    networks:
      - lab_network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: lab6_redis_commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
    depends_on:
      - redis
    networks:
      - lab_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: lab6_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - lab_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: lab6_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - lab_network

  clickhouse:
    image: clickhouse/clickhouse-server:24
    container_name: lab6_clickhouse
    ports:
      - "8123:8123"
    networks:
      - lab_network

<<<<<<< HEAD
  redis_data:
  elastic_data:
  clickhouse_data:

networks:
  lab5-network:
    driver: bridge

networks:
  lab2_network:
    driver: bridge

volumes:
  redis_data:
  elastic_data:
  clickhouse_data:


=======
volumes:
  db_
  redis_
  elastic_
  clickhouse_

networks:
  lab_network:
    driver: bridge
>>>>>>> 52e39ffe47697736954fb2c2fce9efe5f9af046d
