version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: lab5_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
      - kafka
    networks:
      - lab_network

  php:
    build: .
    container_name: lab5_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db
      - kafka
    networks:
      - lab_network

  db:
    image: mysql:8.0
    container_name: lab5_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: student_db
      MYSQL_USER: student_user
      MYSQL_PASSWORD: student_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lab_network

  adminer:
    image: adminer
    container_name: lab5_adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - lab_network

  # Сервисы Kafka (используем официальные образы Confluent)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: lab5_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - lab_network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: lab5_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - lab_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: lab5_kafka_ui
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    ports:
      - "8082:8080"
    networks:
      - lab_network

volumes:
  db_data:

networks:
  lab_network:
    driver: bridge
