version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: lab5_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: unless-stopped
    networks:
      - lab5-network

  php:
    build: .
    container_name: lab5_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    restart: unless-stopped
    networks:
      - lab5-network

  db:
    image: mysql:8.0
    container_name: lab5_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: student_db
      MYSQL_USER: student_user
      MYSQL_PASSWORD: student_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - lab5-network

  adminer:
    image: adminer
    container_name: lab5_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - lab5-network

volumes:
  db_data:

networks:
  lab5-network:
    driver: bridge
