version: '3.8'
services:
  lab5_nginx:
    image: nginx:alpine
    container_name: lab5_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - lab5_php
    restart: unless-stopped
    networks:
      - lab5-network

  lab5_php:
    build: .
    dockerfile: Dockerfile # Убедимся, что используем правильный Dockerfile
    container_name: lab5_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    restart: unless-stopped
    networks:
      - lab5-network
    depends_on:
      - lab5_db
      - lab5_kafka # Добавляем зависимость от Kafka

  lab5_db:
    image: mysql:8.0
    container_name: lab5_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: student_db
      MYSQL_USER: student_user
      MYSQL_PASSWORD: student_pass
    ports:
      - "3307:3306"
    volumes:
      - db_/var/lib/mysql
    restart: unless-stopped
    networks:
      - lab5-network
    command: --default-authentication-plugin=mysql_native_password

  lab5_adminer:
    image: adminer
    container_name: lab5_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - lab5_db
    networks:
      - lab5-network

  # --- Сервисы для ЛР7 (Kafka, вариант 1 - "Регистрация студента") ---
  lab5_zookeeper:
    image: bitnami/zookeeper:latest
    container_name: lab5_zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_/var/lib/zookeeper
    networks:
      - lab5-network

  lab5_kafka:
    image: bitnami/kafka:latest
    container_name: lab5_kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=lab5_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - lab5_zookeeper
    volumes:
      - kafka_/var/lib/kafka
    networks:
      - lab5-network

volumes:
  db_:
  kafka_:
  zookeeper_:

networks:
  lab5-network:
    driver: bridge

