version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: lab6_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - lab6-net

  php:
    build: .
    container_name: lab6_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    networks:
      - lab6-net

  redis:
    image: redis:7
    container_name: lab6_redis
    ports:
      - "6379:6379"
    networks:
      - lab6-net

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: lab6_redis_cmd
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - lab6-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: lab6_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - lab6-net

  clickhouse:
    image: clickhouse/clickhouse-server:24
    container_name: lab6_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - lab6-net

networks:
  lab6-net:
    driver: bridge
